server:
  port: 2200

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka9001.com:9001/eureka/,http://www.eureka9002.com:9002/eureka/
  instance:
    instance-id: SERVICE-HELLO-2200  #别名
    prefer-ip-address: true # 在注册中心显示ip
spring:
  application:
    name: service-hello  # 名称，如果采用服务名称的调用方式，就需要这个名称